config/routes.rb
Rails.application.routes.draw do
  root "tracks#index"
 resources :tracks, only: [:index, :new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/track.rb
class Track < ApplicationRecord
  mount_uploader :attachment, AttachmentUploader
  validates :name, presence: true
  
  def parseGpx
     doc = Nokogiri::XML(open("public/" + self.attachment_url))
     #trackpoints = doc.xpath('//xmlns:trkpt')
     starttime = doc.xpath('//xmlns:time')
     
     if(starttime != nil && starttime.length > 0)
        return Time.xmlschema(starttime[0].text)
     else 
        return ""
     end   
  end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def index
      @tracks = Track.all
   end
   
   def new
      @track = Track.new
   end
   
   def create
      @track = Track.new(track_params)
      @track.starttime = @track.parseGpx()
     
     if @track.save
         redirect_to tracks_path, notice: "Successfully uploaded."
         
       
      else
         render "new"
      end
      
   end
   
   def destroy
      @track = Track.find(params[:id])
      @track.destroy
      redirect_to tracks_path, notice:  "Successfully deleted."
   end
   
   private
      def track_params
      params.require(:track).permit(:name, :attachment)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tracks</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tracks/create.html.erb
<h1>Tracks#create</h1>
<p>Find me in app/views/tracks/create.html.erb</p>

app/views/tracks/destroy.html.erb
<h1>Tracks#destroy</h1>
<p>Find me in app/views/tracks/destroy.html.erb</p>

app/views/tracks/index.html.erb
<div class="container">
<h1>Tracks</h1>
<% if !flash[:notice].blank? %>
   <div>
      <%= flash[:notice] %>
   </div>
<% end %>

<br>
<button type="button" class ="btn">
<%= link_to "New Track", new_track_path %>
</button>
<br>
<br>

<table class="table table-striped table-bordered" >
   <thead>
      <tr>
         <th>Track</th>
         <th>Starttime</th>
         <th>Download Link</th>
         <th>Action</th>
      </tr>
   </thead>
   
   <tbody>
      <% @tracks.each do |track| %>
         
         <tr>
            <td><%= track.name %></td>
            <td><%= track.starttime%></td>
            <td><%= link_to "Download", track.attachment_url, download: ''%> </td> 
           <td><%= button_to "Delete",  track, method: :delete, form:{ data: { turbo_confirm: "Are you sure?"} } %></td>
         </tr>
         
      <% end %>
   </tbody>
   
</table>
</div>

app/views/tracks/new.html.erb
<div class="container">
<h1> Add new track </h1>
<% if !@track.errors.empty? %>
   <div>
      
      <ul>
         <% @track.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
         <% end %>
      </ul>
      
   </div>
<% end %>

<div>
   <%= form_for @track, html: { multipart: true } do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, required: true %>
      <br><br>
      <%= f.label :attachment %>
      <%= f.file_field :attachment, required: true, accept: ".gpx"  %>
      <br>
      <%= f.submit "Save" %>
   <% end %>
        
</div>
</div>